from .auth_routes import *
from .course_routes import *
from .crystal_routes import *
from .enrollment_routes import *
from .lightsaber_routes import *
from .master_routes import *
from .padawan_routes import *
from .species_routes import *
from .temple_routes import *
from .user_routes import *